### PR TITLE
Setting up GitHub page to use the doc's React project

### PR DESCRIPTION
**Pull request by alexjfno1**

### CODE REVIEW

**Comment by peter-mouland** [comment]
@johnsibly the `gh-pages` branch is needed for [http://sky-uk.github.io/nowtv-web-toolkit](github.io) to work

**Comment by alexjfno1** [comment]
@peter-mouland Are you sure? Seems to work just fine without it.

**Comment by peter-mouland** [comment]
@alexjfno1 I've restored the branch - if you delete it again github.io will break.

**Comment by alexjfno1** [comment]
@peter-mouland Ok Thanks, I didn't see that :) Cheers!

**Pull request merged**
